<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="PortedRgTests.catalog" />
    <AdditionalFiles Include="NativeInvalidUtf8RgTests.catalog" />
    <AdditionalFiles Include="NativePcre2RgTests.catalog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scout.Testing\Scout.Testing.csproj" />
    <ProjectReference Include="..\..\src\Scout.App\Scout.App.csproj" />
    <ProjectReference Include="..\..\src\Scout.Os\Scout.Os.csproj" />
  </ItemGroup>

</Project>
