<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.401" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
    <PackageVersion Include="Microsoft.DotNet.ILCompiler"
                    Version="10.0.2"
                    Condition="'$(MSBuildProjectName)' != 'Scout.App' and '$(MSBuildProjectName)' != 'Scout.Entry'" />
    <PackageVersion Include="SharpFuzz" Version="2.3.0" />
  </ItemGroup>
</Project>
