<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <ProjectReference Include="../../src/Scout.Regex/Scout.Regex.csproj" />
    <ProjectReference Include="../../src/Scout.Searching/Scout.Searching.csproj" />
    <ProjectReference Include="../../src/Scout.Ignore/Scout.Ignore.csproj" />
  </ItemGroup>
</Project>
