#!/usr/bin/env python3
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
TABLE_ROOT = ROOT / "upstream" / "regex-syntax-0.8.8" / "unicode_tables"


TABLES = [
    ("DecimalNumber", "perl_decimal.rs", "DECIMAL_NUMBER"),
    ("PerlWord", "perl_word.rs", "PERL_WORD"),
    ("PerlSpace", "perl_space.rs", "WHITE_SPACE"),
    ("Alphabetic", "property_bool.rs", "ALPHABETIC"),
]


PAIR_PATTERN = re.compile(
    r"\(\s*('(?:\\u\{[0-9A-Fa-f]+\}|\\.|[^'])')\s*,\s*('(?:\\u\{[0-9A-Fa-f]+\}|\\.|[^'])')\s*\),?"
)


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    raise SystemExit(1)


def decode_char_literal(literal: str) -> int:
    if len(literal) < 2 or literal[0] != "'" or literal[-1] != "'":
        fail(f"invalid Rust char literal: {literal}")
    body = literal[1:-1]
    if body.startswith(r"\u{") and body.endswith("}"):
        return int(body[3:-1], 16)
    if body.startswith("\\"):
        escapes = {
            r"\0": 0,
            r"\t": 0x09,
            r"\n": 0x0A,
            r"\r": 0x0D,
            r"\\": 0x5C,
            r"\'": 0x27,
            r'\"': 0x22,
        }
        if body in escapes:
            return escapes[body]
        fail(f"unsupported Rust char escape: {literal}")
    if len(body) != 1:
        fail(f"expected one Unicode scalar in {literal}")
    return ord(body)


def load_ranges(file_name: str, const_name: str) -> list[tuple[int, int]]:
    path = TABLE_ROOT / file_name
    text = path.read_text(encoding="utf-8")
    section_pattern = re.compile(
        r"pub const " + re.escape(const_name) + r":.*?=\s*&\[(.*?)\];",
        re.DOTALL,
    )
    match = section_pattern.search(text)
    if not match:
        fail(f"could not find {const_name} in {path}")

    ranges: list[tuple[int, int]] = []
    for pair in PAIR_PATTERN.finditer(match.group(1)):
        start = decode_char_literal(pair.group(1))
        end = decode_char_literal(pair.group(2))
        if start > end:
            fail(f"range start exceeds end in {path}: {pair.group(0)}")
        ranges.append((start, end))

    if not ranges:
        fail(f"no ranges found for {const_name} in {path}")
    if ranges != sorted(ranges):
        fail(f"ranges for {const_name} in {path} are not sorted")
    return ranges


def pascal_case(value: str) -> str:
    return "".join(part.title() for part in value.split("_"))


def load_general_categories() -> list[tuple[str, str, list[tuple[int, int]]]]:
    text = (TABLE_ROOT / "general_category.rs").read_text(encoding="utf-8")
    by_name_match = re.search(r"pub const BY_NAME:.*?= &\[(.*?)\];", text, re.DOTALL)
    if not by_name_match:
        fail("could not find general_category.rs BY_NAME")

    categories = []
    for name, const_name in re.findall(r'\("([^"]+)", ([A-Z_]+)\)', by_name_match.group(1)):
        categories.append((name, pascal_case(name), load_ranges("general_category.rs", const_name)))
    if not categories:
        fail("no general category tables found")
    return categories


def emit_table(name: str, ranges: list[tuple[int, int]]) -> None:
    print(f"    private static readonly UnicodeScalarRange[] {name} =")
    print("    [")
    for start, end in ranges:
        print(f"        new(0x{start:06X}, 0x{end:06X}),")
    print("    ];")
    print()


def main() -> None:
    loaded = [(name, load_ranges(file_name, const_name)) for name, file_name, const_name in TABLES]
    general_categories = load_general_categories()
    print("// <auto-generated />")
    print("// Generated by eng/generate-regex-unicode-tables.py from regex-syntax 0.8.8 Unicode tables.")
    print("// Unicode version: 16.0.0.")
    print("using System;")
    print("using System.Text;")
    print()
    print("namespace Scout;")
    print()
    print("internal static class RegexUnicodeTables")
    print("{")
    print("    internal static bool IsDecimalNumber(Rune value)")
    print("    {")
    print("        return Contains(DecimalNumber, value.Value);")
    print("    }")
    print()
    print("    internal static bool IsPerlWord(Rune value)")
    print("    {")
    print("        return Contains(PerlWord, value.Value);")
    print("    }")
    print()
    print("    internal static bool IsPerlSpace(Rune value)")
    print("    {")
    print("        return Contains(PerlSpace, value.Value);")
    print("    }")
    print()
    print("    internal static bool IsAlphabetic(Rune value)")
    print("    {")
    print("        return Contains(Alphabetic, value.Value);")
    print("    }")
    print()
    print("    internal static bool IsGeneralCategory(RegexUnicodePropertyKind kind, Rune value)")
    print("    {")
    print("        return kind switch")
    print("        {")
    for _, name, _ in general_categories:
        print(f"            RegexUnicodePropertyKind.{name} => Contains(GeneralCategory{name}, value.Value),")
    print("            _ => false,")
    print("        };")
    print("    }")
    print()
    print("    private static bool Contains(ReadOnlySpan<UnicodeScalarRange> ranges, int value)")
    print("    {")
    print("        int low = 0;")
    print("        int high = ranges.Length - 1;")
    print("        while (low <= high)")
    print("        {")
    print("            int middle = low + ((high - low) / 2);")
    print("            UnicodeScalarRange range = ranges[middle];")
    print("            if (value < range.Start)")
    print("            {")
    print("                high = middle - 1;")
    print("                continue;")
    print("            }")
    print()
    print("            if (value > range.End)")
    print("            {")
    print("                low = middle + 1;")
    print("                continue;")
    print("            }")
    print()
    print("            return true;")
    print("        }")
    print()
    print("        return false;")
    print("    }")
    print()
    for name, ranges in loaded:
        emit_table(name, ranges)
    for _, name, ranges in general_categories:
        emit_table("GeneralCategory" + name, ranges)
    print("}")


if __name__ == "__main__":
    main()
