// <auto-generated />
// Generated by eng/generate-regex-unicode-tables.py from regex-syntax 0.8.8 Unicode tables.
// Unicode version: 16.0.0.

namespace Scout;

/// <summary>
/// Resolves generated Unicode Script and Script_Extensions aliases.
/// </summary>
internal static class RegexUnicodeScriptNames
{
    internal static bool TryGetKind(ReadOnlySpan<byte> name, out RegexUnicodeScriptKind kind)
    {
        kind = RegexUnicodeScriptKind.None;
        if (RegexUnicodePropertyNames.NameEquals(name, "adlam"))
        {
            kind = RegexUnicodeScriptKind.Adlam;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "adlm"))
        {
            kind = RegexUnicodeScriptKind.Adlam;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "aghb"))
        {
            kind = RegexUnicodeScriptKind.CaucasianAlbanian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ahom"))
        {
            kind = RegexUnicodeScriptKind.Ahom;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "anatolianhieroglyphs"))
        {
            kind = RegexUnicodeScriptKind.AnatolianHieroglyphs;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "arab"))
        {
            kind = RegexUnicodeScriptKind.Arabic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "arabic"))
        {
            kind = RegexUnicodeScriptKind.Arabic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "armenian"))
        {
            kind = RegexUnicodeScriptKind.Armenian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "armi"))
        {
            kind = RegexUnicodeScriptKind.ImperialAramaic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "armn"))
        {
            kind = RegexUnicodeScriptKind.Armenian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "avestan"))
        {
            kind = RegexUnicodeScriptKind.Avestan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "avst"))
        {
            kind = RegexUnicodeScriptKind.Avestan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bali"))
        {
            kind = RegexUnicodeScriptKind.Balinese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "balinese"))
        {
            kind = RegexUnicodeScriptKind.Balinese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bamu"))
        {
            kind = RegexUnicodeScriptKind.Bamum;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bamum"))
        {
            kind = RegexUnicodeScriptKind.Bamum;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bass"))
        {
            kind = RegexUnicodeScriptKind.BassaVah;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bassavah"))
        {
            kind = RegexUnicodeScriptKind.BassaVah;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "batak"))
        {
            kind = RegexUnicodeScriptKind.Batak;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "batk"))
        {
            kind = RegexUnicodeScriptKind.Batak;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "beng"))
        {
            kind = RegexUnicodeScriptKind.Bengali;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bengali"))
        {
            kind = RegexUnicodeScriptKind.Bengali;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bhaiksuki"))
        {
            kind = RegexUnicodeScriptKind.Bhaiksuki;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bhks"))
        {
            kind = RegexUnicodeScriptKind.Bhaiksuki;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bopo"))
        {
            kind = RegexUnicodeScriptKind.Bopomofo;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bopomofo"))
        {
            kind = RegexUnicodeScriptKind.Bopomofo;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "brah"))
        {
            kind = RegexUnicodeScriptKind.Brahmi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "brahmi"))
        {
            kind = RegexUnicodeScriptKind.Brahmi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "brai"))
        {
            kind = RegexUnicodeScriptKind.Braille;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "braille"))
        {
            kind = RegexUnicodeScriptKind.Braille;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "bugi"))
        {
            kind = RegexUnicodeScriptKind.Buginese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "buginese"))
        {
            kind = RegexUnicodeScriptKind.Buginese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "buhd"))
        {
            kind = RegexUnicodeScriptKind.Buhid;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "buhid"))
        {
            kind = RegexUnicodeScriptKind.Buhid;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cakm"))
        {
            kind = RegexUnicodeScriptKind.Chakma;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "canadianaboriginal"))
        {
            kind = RegexUnicodeScriptKind.CanadianAboriginal;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cans"))
        {
            kind = RegexUnicodeScriptKind.CanadianAboriginal;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cari"))
        {
            kind = RegexUnicodeScriptKind.Carian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "carian"))
        {
            kind = RegexUnicodeScriptKind.Carian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "caucasianalbanian"))
        {
            kind = RegexUnicodeScriptKind.CaucasianAlbanian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "chakma"))
        {
            kind = RegexUnicodeScriptKind.Chakma;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cham"))
        {
            kind = RegexUnicodeScriptKind.Cham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cher"))
        {
            kind = RegexUnicodeScriptKind.Cherokee;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cherokee"))
        {
            kind = RegexUnicodeScriptKind.Cherokee;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "chorasmian"))
        {
            kind = RegexUnicodeScriptKind.Chorasmian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "chrs"))
        {
            kind = RegexUnicodeScriptKind.Chorasmian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "common"))
        {
            kind = RegexUnicodeScriptKind.Common;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "copt"))
        {
            kind = RegexUnicodeScriptKind.Coptic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "coptic"))
        {
            kind = RegexUnicodeScriptKind.Coptic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cpmn"))
        {
            kind = RegexUnicodeScriptKind.CyproMinoan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cprt"))
        {
            kind = RegexUnicodeScriptKind.Cypriot;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cuneiform"))
        {
            kind = RegexUnicodeScriptKind.Cuneiform;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cypriot"))
        {
            kind = RegexUnicodeScriptKind.Cypriot;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cyprominoan"))
        {
            kind = RegexUnicodeScriptKind.CyproMinoan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cyrillic"))
        {
            kind = RegexUnicodeScriptKind.Cyrillic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "cyrl"))
        {
            kind = RegexUnicodeScriptKind.Cyrillic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "deseret"))
        {
            kind = RegexUnicodeScriptKind.Deseret;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "deva"))
        {
            kind = RegexUnicodeScriptKind.Devanagari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "devanagari"))
        {
            kind = RegexUnicodeScriptKind.Devanagari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "diak"))
        {
            kind = RegexUnicodeScriptKind.DivesAkuru;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "divesakuru"))
        {
            kind = RegexUnicodeScriptKind.DivesAkuru;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "dogr"))
        {
            kind = RegexUnicodeScriptKind.Dogra;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "dogra"))
        {
            kind = RegexUnicodeScriptKind.Dogra;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "dsrt"))
        {
            kind = RegexUnicodeScriptKind.Deseret;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "dupl"))
        {
            kind = RegexUnicodeScriptKind.Duployan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "duployan"))
        {
            kind = RegexUnicodeScriptKind.Duployan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "egyp"))
        {
            kind = RegexUnicodeScriptKind.EgyptianHieroglyphs;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "egyptianhieroglyphs"))
        {
            kind = RegexUnicodeScriptKind.EgyptianHieroglyphs;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "elba"))
        {
            kind = RegexUnicodeScriptKind.Elbasan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "elbasan"))
        {
            kind = RegexUnicodeScriptKind.Elbasan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "elym"))
        {
            kind = RegexUnicodeScriptKind.Elymaic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "elymaic"))
        {
            kind = RegexUnicodeScriptKind.Elymaic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ethi"))
        {
            kind = RegexUnicodeScriptKind.Ethiopic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ethiopic"))
        {
            kind = RegexUnicodeScriptKind.Ethiopic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gara"))
        {
            kind = RegexUnicodeScriptKind.Garay;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "garay"))
        {
            kind = RegexUnicodeScriptKind.Garay;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "geor"))
        {
            kind = RegexUnicodeScriptKind.Georgian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "georgian"))
        {
            kind = RegexUnicodeScriptKind.Georgian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "glag"))
        {
            kind = RegexUnicodeScriptKind.Glagolitic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "glagolitic"))
        {
            kind = RegexUnicodeScriptKind.Glagolitic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gong"))
        {
            kind = RegexUnicodeScriptKind.GunjalaGondi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gonm"))
        {
            kind = RegexUnicodeScriptKind.MasaramGondi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "goth"))
        {
            kind = RegexUnicodeScriptKind.Gothic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gothic"))
        {
            kind = RegexUnicodeScriptKind.Gothic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gran"))
        {
            kind = RegexUnicodeScriptKind.Grantha;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "grantha"))
        {
            kind = RegexUnicodeScriptKind.Grantha;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "greek"))
        {
            kind = RegexUnicodeScriptKind.Greek;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "grek"))
        {
            kind = RegexUnicodeScriptKind.Greek;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gujarati"))
        {
            kind = RegexUnicodeScriptKind.Gujarati;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gujr"))
        {
            kind = RegexUnicodeScriptKind.Gujarati;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gukh"))
        {
            kind = RegexUnicodeScriptKind.GurungKhema;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gunjalagondi"))
        {
            kind = RegexUnicodeScriptKind.GunjalaGondi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gurmukhi"))
        {
            kind = RegexUnicodeScriptKind.Gurmukhi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "guru"))
        {
            kind = RegexUnicodeScriptKind.Gurmukhi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "gurungkhema"))
        {
            kind = RegexUnicodeScriptKind.GurungKhema;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "han"))
        {
            kind = RegexUnicodeScriptKind.Han;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hang"))
        {
            kind = RegexUnicodeScriptKind.Hangul;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hangul"))
        {
            kind = RegexUnicodeScriptKind.Hangul;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hani"))
        {
            kind = RegexUnicodeScriptKind.Han;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hanifirohingya"))
        {
            kind = RegexUnicodeScriptKind.HanifiRohingya;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hano"))
        {
            kind = RegexUnicodeScriptKind.Hanunoo;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hanunoo"))
        {
            kind = RegexUnicodeScriptKind.Hanunoo;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hatr"))
        {
            kind = RegexUnicodeScriptKind.Hatran;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hatran"))
        {
            kind = RegexUnicodeScriptKind.Hatran;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hebr"))
        {
            kind = RegexUnicodeScriptKind.Hebrew;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hebrew"))
        {
            kind = RegexUnicodeScriptKind.Hebrew;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hira"))
        {
            kind = RegexUnicodeScriptKind.Hiragana;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hiragana"))
        {
            kind = RegexUnicodeScriptKind.Hiragana;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hluw"))
        {
            kind = RegexUnicodeScriptKind.AnatolianHieroglyphs;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hmng"))
        {
            kind = RegexUnicodeScriptKind.PahawhHmong;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hmnp"))
        {
            kind = RegexUnicodeScriptKind.NyiakengPuachueHmong;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "hung"))
        {
            kind = RegexUnicodeScriptKind.OldHungarian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "imperialaramaic"))
        {
            kind = RegexUnicodeScriptKind.ImperialAramaic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "inherited"))
        {
            kind = RegexUnicodeScriptKind.Inherited;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "inscriptionalpahlavi"))
        {
            kind = RegexUnicodeScriptKind.InscriptionalPahlavi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "inscriptionalparthian"))
        {
            kind = RegexUnicodeScriptKind.InscriptionalParthian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ital"))
        {
            kind = RegexUnicodeScriptKind.OldItalic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "java"))
        {
            kind = RegexUnicodeScriptKind.Javanese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "javanese"))
        {
            kind = RegexUnicodeScriptKind.Javanese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kaithi"))
        {
            kind = RegexUnicodeScriptKind.Kaithi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kali"))
        {
            kind = RegexUnicodeScriptKind.KayahLi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kana"))
        {
            kind = RegexUnicodeScriptKind.Katakana;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kannada"))
        {
            kind = RegexUnicodeScriptKind.Kannada;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "katakana"))
        {
            kind = RegexUnicodeScriptKind.Katakana;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kawi"))
        {
            kind = RegexUnicodeScriptKind.Kawi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kayahli"))
        {
            kind = RegexUnicodeScriptKind.KayahLi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khar"))
        {
            kind = RegexUnicodeScriptKind.Kharoshthi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kharoshthi"))
        {
            kind = RegexUnicodeScriptKind.Kharoshthi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khitansmallscript"))
        {
            kind = RegexUnicodeScriptKind.KhitanSmallScript;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khmer"))
        {
            kind = RegexUnicodeScriptKind.Khmer;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khmr"))
        {
            kind = RegexUnicodeScriptKind.Khmer;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khoj"))
        {
            kind = RegexUnicodeScriptKind.Khojki;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khojki"))
        {
            kind = RegexUnicodeScriptKind.Khojki;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "khudawadi"))
        {
            kind = RegexUnicodeScriptKind.Khudawadi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kiratrai"))
        {
            kind = RegexUnicodeScriptKind.KiratRai;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kits"))
        {
            kind = RegexUnicodeScriptKind.KhitanSmallScript;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "knda"))
        {
            kind = RegexUnicodeScriptKind.Kannada;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "krai"))
        {
            kind = RegexUnicodeScriptKind.KiratRai;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "kthi"))
        {
            kind = RegexUnicodeScriptKind.Kaithi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lana"))
        {
            kind = RegexUnicodeScriptKind.TaiTham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lao"))
        {
            kind = RegexUnicodeScriptKind.Lao;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "laoo"))
        {
            kind = RegexUnicodeScriptKind.Lao;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "latin"))
        {
            kind = RegexUnicodeScriptKind.Latin;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "latn"))
        {
            kind = RegexUnicodeScriptKind.Latin;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lepc"))
        {
            kind = RegexUnicodeScriptKind.Lepcha;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lepcha"))
        {
            kind = RegexUnicodeScriptKind.Lepcha;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "limb"))
        {
            kind = RegexUnicodeScriptKind.Limbu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "limbu"))
        {
            kind = RegexUnicodeScriptKind.Limbu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lina"))
        {
            kind = RegexUnicodeScriptKind.LinearA;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "linb"))
        {
            kind = RegexUnicodeScriptKind.LinearB;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lineara"))
        {
            kind = RegexUnicodeScriptKind.LinearA;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "linearb"))
        {
            kind = RegexUnicodeScriptKind.LinearB;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lisu"))
        {
            kind = RegexUnicodeScriptKind.Lisu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lyci"))
        {
            kind = RegexUnicodeScriptKind.Lycian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lycian"))
        {
            kind = RegexUnicodeScriptKind.Lycian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lydi"))
        {
            kind = RegexUnicodeScriptKind.Lydian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "lydian"))
        {
            kind = RegexUnicodeScriptKind.Lydian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mahajani"))
        {
            kind = RegexUnicodeScriptKind.Mahajani;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mahj"))
        {
            kind = RegexUnicodeScriptKind.Mahajani;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "maka"))
        {
            kind = RegexUnicodeScriptKind.Makasar;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "makasar"))
        {
            kind = RegexUnicodeScriptKind.Makasar;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "malayalam"))
        {
            kind = RegexUnicodeScriptKind.Malayalam;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mand"))
        {
            kind = RegexUnicodeScriptKind.Mandaic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mandaic"))
        {
            kind = RegexUnicodeScriptKind.Mandaic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mani"))
        {
            kind = RegexUnicodeScriptKind.Manichaean;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "manichaean"))
        {
            kind = RegexUnicodeScriptKind.Manichaean;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "marc"))
        {
            kind = RegexUnicodeScriptKind.Marchen;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "marchen"))
        {
            kind = RegexUnicodeScriptKind.Marchen;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "masaramgondi"))
        {
            kind = RegexUnicodeScriptKind.MasaramGondi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "medefaidrin"))
        {
            kind = RegexUnicodeScriptKind.Medefaidrin;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "medf"))
        {
            kind = RegexUnicodeScriptKind.Medefaidrin;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "meeteimayek"))
        {
            kind = RegexUnicodeScriptKind.MeeteiMayek;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mend"))
        {
            kind = RegexUnicodeScriptKind.MendeKikakui;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mendekikakui"))
        {
            kind = RegexUnicodeScriptKind.MendeKikakui;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "merc"))
        {
            kind = RegexUnicodeScriptKind.MeroiticCursive;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mero"))
        {
            kind = RegexUnicodeScriptKind.MeroiticHieroglyphs;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "meroiticcursive"))
        {
            kind = RegexUnicodeScriptKind.MeroiticCursive;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "meroitichieroglyphs"))
        {
            kind = RegexUnicodeScriptKind.MeroiticHieroglyphs;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "miao"))
        {
            kind = RegexUnicodeScriptKind.Miao;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mlym"))
        {
            kind = RegexUnicodeScriptKind.Malayalam;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "modi"))
        {
            kind = RegexUnicodeScriptKind.Modi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mong"))
        {
            kind = RegexUnicodeScriptKind.Mongolian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mongolian"))
        {
            kind = RegexUnicodeScriptKind.Mongolian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mro"))
        {
            kind = RegexUnicodeScriptKind.Mro;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mroo"))
        {
            kind = RegexUnicodeScriptKind.Mro;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mtei"))
        {
            kind = RegexUnicodeScriptKind.MeeteiMayek;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mult"))
        {
            kind = RegexUnicodeScriptKind.Multani;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "multani"))
        {
            kind = RegexUnicodeScriptKind.Multani;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "myanmar"))
        {
            kind = RegexUnicodeScriptKind.Myanmar;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "mymr"))
        {
            kind = RegexUnicodeScriptKind.Myanmar;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nabataean"))
        {
            kind = RegexUnicodeScriptKind.Nabataean;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nagm"))
        {
            kind = RegexUnicodeScriptKind.NagMundari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nagmundari"))
        {
            kind = RegexUnicodeScriptKind.NagMundari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nand"))
        {
            kind = RegexUnicodeScriptKind.Nandinagari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nandinagari"))
        {
            kind = RegexUnicodeScriptKind.Nandinagari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "narb"))
        {
            kind = RegexUnicodeScriptKind.OldNorthArabian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nbat"))
        {
            kind = RegexUnicodeScriptKind.Nabataean;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "newa"))
        {
            kind = RegexUnicodeScriptKind.Newa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "newtailue"))
        {
            kind = RegexUnicodeScriptKind.NewTaiLue;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nko"))
        {
            kind = RegexUnicodeScriptKind.Nko;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nkoo"))
        {
            kind = RegexUnicodeScriptKind.Nko;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nshu"))
        {
            kind = RegexUnicodeScriptKind.Nushu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nushu"))
        {
            kind = RegexUnicodeScriptKind.Nushu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "nyiakengpuachuehmong"))
        {
            kind = RegexUnicodeScriptKind.NyiakengPuachueHmong;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ogam"))
        {
            kind = RegexUnicodeScriptKind.Ogham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ogham"))
        {
            kind = RegexUnicodeScriptKind.Ogham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "olchiki"))
        {
            kind = RegexUnicodeScriptKind.OlChiki;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "olck"))
        {
            kind = RegexUnicodeScriptKind.OlChiki;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldhungarian"))
        {
            kind = RegexUnicodeScriptKind.OldHungarian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "olditalic"))
        {
            kind = RegexUnicodeScriptKind.OldItalic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldnortharabian"))
        {
            kind = RegexUnicodeScriptKind.OldNorthArabian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldpermic"))
        {
            kind = RegexUnicodeScriptKind.OldPermic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldpersian"))
        {
            kind = RegexUnicodeScriptKind.OldPersian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldsogdian"))
        {
            kind = RegexUnicodeScriptKind.OldSogdian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldsoutharabian"))
        {
            kind = RegexUnicodeScriptKind.OldSouthArabian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oldturkic"))
        {
            kind = RegexUnicodeScriptKind.OldTurkic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "olduyghur"))
        {
            kind = RegexUnicodeScriptKind.OldUyghur;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "olonal"))
        {
            kind = RegexUnicodeScriptKind.OlOnal;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "onao"))
        {
            kind = RegexUnicodeScriptKind.OlOnal;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "oriya"))
        {
            kind = RegexUnicodeScriptKind.Oriya;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "orkh"))
        {
            kind = RegexUnicodeScriptKind.OldTurkic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "orya"))
        {
            kind = RegexUnicodeScriptKind.Oriya;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "osage"))
        {
            kind = RegexUnicodeScriptKind.Osage;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "osge"))
        {
            kind = RegexUnicodeScriptKind.Osage;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "osma"))
        {
            kind = RegexUnicodeScriptKind.Osmanya;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "osmanya"))
        {
            kind = RegexUnicodeScriptKind.Osmanya;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ougr"))
        {
            kind = RegexUnicodeScriptKind.OldUyghur;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "pahawhhmong"))
        {
            kind = RegexUnicodeScriptKind.PahawhHmong;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "palm"))
        {
            kind = RegexUnicodeScriptKind.Palmyrene;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "palmyrene"))
        {
            kind = RegexUnicodeScriptKind.Palmyrene;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "pauc"))
        {
            kind = RegexUnicodeScriptKind.PauCinHau;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "paucinhau"))
        {
            kind = RegexUnicodeScriptKind.PauCinHau;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "perm"))
        {
            kind = RegexUnicodeScriptKind.OldPermic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "phag"))
        {
            kind = RegexUnicodeScriptKind.PhagsPa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "phagspa"))
        {
            kind = RegexUnicodeScriptKind.PhagsPa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "phli"))
        {
            kind = RegexUnicodeScriptKind.InscriptionalPahlavi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "phlp"))
        {
            kind = RegexUnicodeScriptKind.PsalterPahlavi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "phnx"))
        {
            kind = RegexUnicodeScriptKind.Phoenician;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "phoenician"))
        {
            kind = RegexUnicodeScriptKind.Phoenician;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "plrd"))
        {
            kind = RegexUnicodeScriptKind.Miao;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "prti"))
        {
            kind = RegexUnicodeScriptKind.InscriptionalParthian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "psalterpahlavi"))
        {
            kind = RegexUnicodeScriptKind.PsalterPahlavi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "qaac"))
        {
            kind = RegexUnicodeScriptKind.Coptic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "qaai"))
        {
            kind = RegexUnicodeScriptKind.Inherited;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "rejang"))
        {
            kind = RegexUnicodeScriptKind.Rejang;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "rjng"))
        {
            kind = RegexUnicodeScriptKind.Rejang;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "rohg"))
        {
            kind = RegexUnicodeScriptKind.HanifiRohingya;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "runic"))
        {
            kind = RegexUnicodeScriptKind.Runic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "runr"))
        {
            kind = RegexUnicodeScriptKind.Runic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "samaritan"))
        {
            kind = RegexUnicodeScriptKind.Samaritan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "samr"))
        {
            kind = RegexUnicodeScriptKind.Samaritan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sarb"))
        {
            kind = RegexUnicodeScriptKind.OldSouthArabian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "saur"))
        {
            kind = RegexUnicodeScriptKind.Saurashtra;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "saurashtra"))
        {
            kind = RegexUnicodeScriptKind.Saurashtra;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sgnw"))
        {
            kind = RegexUnicodeScriptKind.Signwriting;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sharada"))
        {
            kind = RegexUnicodeScriptKind.Sharada;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "shavian"))
        {
            kind = RegexUnicodeScriptKind.Shavian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "shaw"))
        {
            kind = RegexUnicodeScriptKind.Shavian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "shrd"))
        {
            kind = RegexUnicodeScriptKind.Sharada;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sidd"))
        {
            kind = RegexUnicodeScriptKind.Siddham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "siddham"))
        {
            kind = RegexUnicodeScriptKind.Siddham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "signwriting"))
        {
            kind = RegexUnicodeScriptKind.Signwriting;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sind"))
        {
            kind = RegexUnicodeScriptKind.Khudawadi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sinh"))
        {
            kind = RegexUnicodeScriptKind.Sinhala;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sinhala"))
        {
            kind = RegexUnicodeScriptKind.Sinhala;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sogd"))
        {
            kind = RegexUnicodeScriptKind.Sogdian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sogdian"))
        {
            kind = RegexUnicodeScriptKind.Sogdian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sogo"))
        {
            kind = RegexUnicodeScriptKind.OldSogdian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sora"))
        {
            kind = RegexUnicodeScriptKind.SoraSompeng;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sorasompeng"))
        {
            kind = RegexUnicodeScriptKind.SoraSompeng;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "soyo"))
        {
            kind = RegexUnicodeScriptKind.Soyombo;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "soyombo"))
        {
            kind = RegexUnicodeScriptKind.Soyombo;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sund"))
        {
            kind = RegexUnicodeScriptKind.Sundanese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sundanese"))
        {
            kind = RegexUnicodeScriptKind.Sundanese;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sunu"))
        {
            kind = RegexUnicodeScriptKind.Sunuwar;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sunuwar"))
        {
            kind = RegexUnicodeScriptKind.Sunuwar;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sylo"))
        {
            kind = RegexUnicodeScriptKind.SylotiNagri;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "sylotinagri"))
        {
            kind = RegexUnicodeScriptKind.SylotiNagri;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "syrc"))
        {
            kind = RegexUnicodeScriptKind.Syriac;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "syriac"))
        {
            kind = RegexUnicodeScriptKind.Syriac;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tagalog"))
        {
            kind = RegexUnicodeScriptKind.Tagalog;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tagb"))
        {
            kind = RegexUnicodeScriptKind.Tagbanwa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tagbanwa"))
        {
            kind = RegexUnicodeScriptKind.Tagbanwa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "taile"))
        {
            kind = RegexUnicodeScriptKind.TaiLe;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "taitham"))
        {
            kind = RegexUnicodeScriptKind.TaiTham;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "taiviet"))
        {
            kind = RegexUnicodeScriptKind.TaiViet;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "takr"))
        {
            kind = RegexUnicodeScriptKind.Takri;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "takri"))
        {
            kind = RegexUnicodeScriptKind.Takri;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tale"))
        {
            kind = RegexUnicodeScriptKind.TaiLe;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "talu"))
        {
            kind = RegexUnicodeScriptKind.NewTaiLue;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tamil"))
        {
            kind = RegexUnicodeScriptKind.Tamil;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "taml"))
        {
            kind = RegexUnicodeScriptKind.Tamil;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tang"))
        {
            kind = RegexUnicodeScriptKind.Tangut;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tangsa"))
        {
            kind = RegexUnicodeScriptKind.Tangsa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tangut"))
        {
            kind = RegexUnicodeScriptKind.Tangut;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tavt"))
        {
            kind = RegexUnicodeScriptKind.TaiViet;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "telu"))
        {
            kind = RegexUnicodeScriptKind.Telugu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "telugu"))
        {
            kind = RegexUnicodeScriptKind.Telugu;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tfng"))
        {
            kind = RegexUnicodeScriptKind.Tifinagh;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tglg"))
        {
            kind = RegexUnicodeScriptKind.Tagalog;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "thaa"))
        {
            kind = RegexUnicodeScriptKind.Thaana;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "thaana"))
        {
            kind = RegexUnicodeScriptKind.Thaana;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "thai"))
        {
            kind = RegexUnicodeScriptKind.Thai;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tibetan"))
        {
            kind = RegexUnicodeScriptKind.Tibetan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tibt"))
        {
            kind = RegexUnicodeScriptKind.Tibetan;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tifinagh"))
        {
            kind = RegexUnicodeScriptKind.Tifinagh;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tirh"))
        {
            kind = RegexUnicodeScriptKind.Tirhuta;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tirhuta"))
        {
            kind = RegexUnicodeScriptKind.Tirhuta;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tnsa"))
        {
            kind = RegexUnicodeScriptKind.Tangsa;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "todhri"))
        {
            kind = RegexUnicodeScriptKind.Todhri;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "todr"))
        {
            kind = RegexUnicodeScriptKind.Todhri;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "toto"))
        {
            kind = RegexUnicodeScriptKind.Toto;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tulutigalari"))
        {
            kind = RegexUnicodeScriptKind.TuluTigalari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "tutg"))
        {
            kind = RegexUnicodeScriptKind.TuluTigalari;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ugar"))
        {
            kind = RegexUnicodeScriptKind.Ugaritic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "ugaritic"))
        {
            kind = RegexUnicodeScriptKind.Ugaritic;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "vai"))
        {
            kind = RegexUnicodeScriptKind.Vai;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "vaii"))
        {
            kind = RegexUnicodeScriptKind.Vai;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "vith"))
        {
            kind = RegexUnicodeScriptKind.Vithkuqi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "vithkuqi"))
        {
            kind = RegexUnicodeScriptKind.Vithkuqi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "wancho"))
        {
            kind = RegexUnicodeScriptKind.Wancho;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "wara"))
        {
            kind = RegexUnicodeScriptKind.WarangCiti;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "warangciti"))
        {
            kind = RegexUnicodeScriptKind.WarangCiti;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "wcho"))
        {
            kind = RegexUnicodeScriptKind.Wancho;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "xpeo"))
        {
            kind = RegexUnicodeScriptKind.OldPersian;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "xsux"))
        {
            kind = RegexUnicodeScriptKind.Cuneiform;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "yezi"))
        {
            kind = RegexUnicodeScriptKind.Yezidi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "yezidi"))
        {
            kind = RegexUnicodeScriptKind.Yezidi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "yi"))
        {
            kind = RegexUnicodeScriptKind.Yi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "yiii"))
        {
            kind = RegexUnicodeScriptKind.Yi;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "zanabazarsquare"))
        {
            kind = RegexUnicodeScriptKind.ZanabazarSquare;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "zanb"))
        {
            kind = RegexUnicodeScriptKind.ZanabazarSquare;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "zinh"))
        {
            kind = RegexUnicodeScriptKind.Inherited;
            return true;
        }

        if (RegexUnicodePropertyNames.NameEquals(name, "zyyy"))
        {
            kind = RegexUnicodeScriptKind.Common;
            return true;
        }

        return false;
    }
}
