// <auto-generated />
// Generated by eng/generate-regex-unicode-tables.py from regex-syntax 0.8.8 Unicode tables.
// Unicode version: 16.0.0.

namespace Scout;

/// <summary>
/// Identifies a generated Unicode Script or Script_Extensions value.
/// </summary>
internal enum RegexUnicodeScriptKind
{
    /// <summary>
    /// Identifies the absence of a Unicode script value.
    /// </summary>
    None,

    /// <summary>
    /// Identifies the Adlam Unicode script.
    /// </summary>
    Adlam,

    /// <summary>
    /// Identifies the Ahom Unicode script.
    /// </summary>
    Ahom,

    /// <summary>
    /// Identifies the AnatolianHieroglyphs Unicode script.
    /// </summary>
    AnatolianHieroglyphs,

    /// <summary>
    /// Identifies the Arabic Unicode script.
    /// </summary>
    Arabic,

    /// <summary>
    /// Identifies the Armenian Unicode script.
    /// </summary>
    Armenian,

    /// <summary>
    /// Identifies the Avestan Unicode script.
    /// </summary>
    Avestan,

    /// <summary>
    /// Identifies the Balinese Unicode script.
    /// </summary>
    Balinese,

    /// <summary>
    /// Identifies the Bamum Unicode script.
    /// </summary>
    Bamum,

    /// <summary>
    /// Identifies the BassaVah Unicode script.
    /// </summary>
    BassaVah,

    /// <summary>
    /// Identifies the Batak Unicode script.
    /// </summary>
    Batak,

    /// <summary>
    /// Identifies the Bengali Unicode script.
    /// </summary>
    Bengali,

    /// <summary>
    /// Identifies the Bhaiksuki Unicode script.
    /// </summary>
    Bhaiksuki,

    /// <summary>
    /// Identifies the Bopomofo Unicode script.
    /// </summary>
    Bopomofo,

    /// <summary>
    /// Identifies the Brahmi Unicode script.
    /// </summary>
    Brahmi,

    /// <summary>
    /// Identifies the Braille Unicode script.
    /// </summary>
    Braille,

    /// <summary>
    /// Identifies the Buginese Unicode script.
    /// </summary>
    Buginese,

    /// <summary>
    /// Identifies the Buhid Unicode script.
    /// </summary>
    Buhid,

    /// <summary>
    /// Identifies the CanadianAboriginal Unicode script.
    /// </summary>
    CanadianAboriginal,

    /// <summary>
    /// Identifies the Carian Unicode script.
    /// </summary>
    Carian,

    /// <summary>
    /// Identifies the CaucasianAlbanian Unicode script.
    /// </summary>
    CaucasianAlbanian,

    /// <summary>
    /// Identifies the Chakma Unicode script.
    /// </summary>
    Chakma,

    /// <summary>
    /// Identifies the Cham Unicode script.
    /// </summary>
    Cham,

    /// <summary>
    /// Identifies the Cherokee Unicode script.
    /// </summary>
    Cherokee,

    /// <summary>
    /// Identifies the Chorasmian Unicode script.
    /// </summary>
    Chorasmian,

    /// <summary>
    /// Identifies the Common Unicode script.
    /// </summary>
    Common,

    /// <summary>
    /// Identifies the Coptic Unicode script.
    /// </summary>
    Coptic,

    /// <summary>
    /// Identifies the Cuneiform Unicode script.
    /// </summary>
    Cuneiform,

    /// <summary>
    /// Identifies the Cypriot Unicode script.
    /// </summary>
    Cypriot,

    /// <summary>
    /// Identifies the CyproMinoan Unicode script.
    /// </summary>
    CyproMinoan,

    /// <summary>
    /// Identifies the Cyrillic Unicode script.
    /// </summary>
    Cyrillic,

    /// <summary>
    /// Identifies the Deseret Unicode script.
    /// </summary>
    Deseret,

    /// <summary>
    /// Identifies the Devanagari Unicode script.
    /// </summary>
    Devanagari,

    /// <summary>
    /// Identifies the DivesAkuru Unicode script.
    /// </summary>
    DivesAkuru,

    /// <summary>
    /// Identifies the Dogra Unicode script.
    /// </summary>
    Dogra,

    /// <summary>
    /// Identifies the Duployan Unicode script.
    /// </summary>
    Duployan,

    /// <summary>
    /// Identifies the EgyptianHieroglyphs Unicode script.
    /// </summary>
    EgyptianHieroglyphs,

    /// <summary>
    /// Identifies the Elbasan Unicode script.
    /// </summary>
    Elbasan,

    /// <summary>
    /// Identifies the Elymaic Unicode script.
    /// </summary>
    Elymaic,

    /// <summary>
    /// Identifies the Ethiopic Unicode script.
    /// </summary>
    Ethiopic,

    /// <summary>
    /// Identifies the Garay Unicode script.
    /// </summary>
    Garay,

    /// <summary>
    /// Identifies the Georgian Unicode script.
    /// </summary>
    Georgian,

    /// <summary>
    /// Identifies the Glagolitic Unicode script.
    /// </summary>
    Glagolitic,

    /// <summary>
    /// Identifies the Gothic Unicode script.
    /// </summary>
    Gothic,

    /// <summary>
    /// Identifies the Grantha Unicode script.
    /// </summary>
    Grantha,

    /// <summary>
    /// Identifies the Greek Unicode script.
    /// </summary>
    Greek,

    /// <summary>
    /// Identifies the Gujarati Unicode script.
    /// </summary>
    Gujarati,

    /// <summary>
    /// Identifies the GunjalaGondi Unicode script.
    /// </summary>
    GunjalaGondi,

    /// <summary>
    /// Identifies the Gurmukhi Unicode script.
    /// </summary>
    Gurmukhi,

    /// <summary>
    /// Identifies the GurungKhema Unicode script.
    /// </summary>
    GurungKhema,

    /// <summary>
    /// Identifies the Han Unicode script.
    /// </summary>
    Han,

    /// <summary>
    /// Identifies the Hangul Unicode script.
    /// </summary>
    Hangul,

    /// <summary>
    /// Identifies the HanifiRohingya Unicode script.
    /// </summary>
    HanifiRohingya,

    /// <summary>
    /// Identifies the Hanunoo Unicode script.
    /// </summary>
    Hanunoo,

    /// <summary>
    /// Identifies the Hatran Unicode script.
    /// </summary>
    Hatran,

    /// <summary>
    /// Identifies the Hebrew Unicode script.
    /// </summary>
    Hebrew,

    /// <summary>
    /// Identifies the Hiragana Unicode script.
    /// </summary>
    Hiragana,

    /// <summary>
    /// Identifies the ImperialAramaic Unicode script.
    /// </summary>
    ImperialAramaic,

    /// <summary>
    /// Identifies the Inherited Unicode script.
    /// </summary>
    Inherited,

    /// <summary>
    /// Identifies the InscriptionalPahlavi Unicode script.
    /// </summary>
    InscriptionalPahlavi,

    /// <summary>
    /// Identifies the InscriptionalParthian Unicode script.
    /// </summary>
    InscriptionalParthian,

    /// <summary>
    /// Identifies the Javanese Unicode script.
    /// </summary>
    Javanese,

    /// <summary>
    /// Identifies the Kaithi Unicode script.
    /// </summary>
    Kaithi,

    /// <summary>
    /// Identifies the Kannada Unicode script.
    /// </summary>
    Kannada,

    /// <summary>
    /// Identifies the Katakana Unicode script.
    /// </summary>
    Katakana,

    /// <summary>
    /// Identifies the Kawi Unicode script.
    /// </summary>
    Kawi,

    /// <summary>
    /// Identifies the KayahLi Unicode script.
    /// </summary>
    KayahLi,

    /// <summary>
    /// Identifies the Kharoshthi Unicode script.
    /// </summary>
    Kharoshthi,

    /// <summary>
    /// Identifies the KhitanSmallScript Unicode script.
    /// </summary>
    KhitanSmallScript,

    /// <summary>
    /// Identifies the Khmer Unicode script.
    /// </summary>
    Khmer,

    /// <summary>
    /// Identifies the Khojki Unicode script.
    /// </summary>
    Khojki,

    /// <summary>
    /// Identifies the Khudawadi Unicode script.
    /// </summary>
    Khudawadi,

    /// <summary>
    /// Identifies the KiratRai Unicode script.
    /// </summary>
    KiratRai,

    /// <summary>
    /// Identifies the Lao Unicode script.
    /// </summary>
    Lao,

    /// <summary>
    /// Identifies the Latin Unicode script.
    /// </summary>
    Latin,

    /// <summary>
    /// Identifies the Lepcha Unicode script.
    /// </summary>
    Lepcha,

    /// <summary>
    /// Identifies the Limbu Unicode script.
    /// </summary>
    Limbu,

    /// <summary>
    /// Identifies the LinearA Unicode script.
    /// </summary>
    LinearA,

    /// <summary>
    /// Identifies the LinearB Unicode script.
    /// </summary>
    LinearB,

    /// <summary>
    /// Identifies the Lisu Unicode script.
    /// </summary>
    Lisu,

    /// <summary>
    /// Identifies the Lycian Unicode script.
    /// </summary>
    Lycian,

    /// <summary>
    /// Identifies the Lydian Unicode script.
    /// </summary>
    Lydian,

    /// <summary>
    /// Identifies the Mahajani Unicode script.
    /// </summary>
    Mahajani,

    /// <summary>
    /// Identifies the Makasar Unicode script.
    /// </summary>
    Makasar,

    /// <summary>
    /// Identifies the Malayalam Unicode script.
    /// </summary>
    Malayalam,

    /// <summary>
    /// Identifies the Mandaic Unicode script.
    /// </summary>
    Mandaic,

    /// <summary>
    /// Identifies the Manichaean Unicode script.
    /// </summary>
    Manichaean,

    /// <summary>
    /// Identifies the Marchen Unicode script.
    /// </summary>
    Marchen,

    /// <summary>
    /// Identifies the MasaramGondi Unicode script.
    /// </summary>
    MasaramGondi,

    /// <summary>
    /// Identifies the Medefaidrin Unicode script.
    /// </summary>
    Medefaidrin,

    /// <summary>
    /// Identifies the MeeteiMayek Unicode script.
    /// </summary>
    MeeteiMayek,

    /// <summary>
    /// Identifies the MendeKikakui Unicode script.
    /// </summary>
    MendeKikakui,

    /// <summary>
    /// Identifies the MeroiticCursive Unicode script.
    /// </summary>
    MeroiticCursive,

    /// <summary>
    /// Identifies the MeroiticHieroglyphs Unicode script.
    /// </summary>
    MeroiticHieroglyphs,

    /// <summary>
    /// Identifies the Miao Unicode script.
    /// </summary>
    Miao,

    /// <summary>
    /// Identifies the Modi Unicode script.
    /// </summary>
    Modi,

    /// <summary>
    /// Identifies the Mongolian Unicode script.
    /// </summary>
    Mongolian,

    /// <summary>
    /// Identifies the Mro Unicode script.
    /// </summary>
    Mro,

    /// <summary>
    /// Identifies the Multani Unicode script.
    /// </summary>
    Multani,

    /// <summary>
    /// Identifies the Myanmar Unicode script.
    /// </summary>
    Myanmar,

    /// <summary>
    /// Identifies the Nabataean Unicode script.
    /// </summary>
    Nabataean,

    /// <summary>
    /// Identifies the NagMundari Unicode script.
    /// </summary>
    NagMundari,

    /// <summary>
    /// Identifies the Nandinagari Unicode script.
    /// </summary>
    Nandinagari,

    /// <summary>
    /// Identifies the NewTaiLue Unicode script.
    /// </summary>
    NewTaiLue,

    /// <summary>
    /// Identifies the Newa Unicode script.
    /// </summary>
    Newa,

    /// <summary>
    /// Identifies the Nko Unicode script.
    /// </summary>
    Nko,

    /// <summary>
    /// Identifies the Nushu Unicode script.
    /// </summary>
    Nushu,

    /// <summary>
    /// Identifies the NyiakengPuachueHmong Unicode script.
    /// </summary>
    NyiakengPuachueHmong,

    /// <summary>
    /// Identifies the Ogham Unicode script.
    /// </summary>
    Ogham,

    /// <summary>
    /// Identifies the OlChiki Unicode script.
    /// </summary>
    OlChiki,

    /// <summary>
    /// Identifies the OlOnal Unicode script.
    /// </summary>
    OlOnal,

    /// <summary>
    /// Identifies the OldHungarian Unicode script.
    /// </summary>
    OldHungarian,

    /// <summary>
    /// Identifies the OldItalic Unicode script.
    /// </summary>
    OldItalic,

    /// <summary>
    /// Identifies the OldNorthArabian Unicode script.
    /// </summary>
    OldNorthArabian,

    /// <summary>
    /// Identifies the OldPermic Unicode script.
    /// </summary>
    OldPermic,

    /// <summary>
    /// Identifies the OldPersian Unicode script.
    /// </summary>
    OldPersian,

    /// <summary>
    /// Identifies the OldSogdian Unicode script.
    /// </summary>
    OldSogdian,

    /// <summary>
    /// Identifies the OldSouthArabian Unicode script.
    /// </summary>
    OldSouthArabian,

    /// <summary>
    /// Identifies the OldTurkic Unicode script.
    /// </summary>
    OldTurkic,

    /// <summary>
    /// Identifies the OldUyghur Unicode script.
    /// </summary>
    OldUyghur,

    /// <summary>
    /// Identifies the Oriya Unicode script.
    /// </summary>
    Oriya,

    /// <summary>
    /// Identifies the Osage Unicode script.
    /// </summary>
    Osage,

    /// <summary>
    /// Identifies the Osmanya Unicode script.
    /// </summary>
    Osmanya,

    /// <summary>
    /// Identifies the PahawhHmong Unicode script.
    /// </summary>
    PahawhHmong,

    /// <summary>
    /// Identifies the Palmyrene Unicode script.
    /// </summary>
    Palmyrene,

    /// <summary>
    /// Identifies the PauCinHau Unicode script.
    /// </summary>
    PauCinHau,

    /// <summary>
    /// Identifies the PhagsPa Unicode script.
    /// </summary>
    PhagsPa,

    /// <summary>
    /// Identifies the Phoenician Unicode script.
    /// </summary>
    Phoenician,

    /// <summary>
    /// Identifies the PsalterPahlavi Unicode script.
    /// </summary>
    PsalterPahlavi,

    /// <summary>
    /// Identifies the Rejang Unicode script.
    /// </summary>
    Rejang,

    /// <summary>
    /// Identifies the Runic Unicode script.
    /// </summary>
    Runic,

    /// <summary>
    /// Identifies the Samaritan Unicode script.
    /// </summary>
    Samaritan,

    /// <summary>
    /// Identifies the Saurashtra Unicode script.
    /// </summary>
    Saurashtra,

    /// <summary>
    /// Identifies the Sharada Unicode script.
    /// </summary>
    Sharada,

    /// <summary>
    /// Identifies the Shavian Unicode script.
    /// </summary>
    Shavian,

    /// <summary>
    /// Identifies the Siddham Unicode script.
    /// </summary>
    Siddham,

    /// <summary>
    /// Identifies the Signwriting Unicode script.
    /// </summary>
    Signwriting,

    /// <summary>
    /// Identifies the Sinhala Unicode script.
    /// </summary>
    Sinhala,

    /// <summary>
    /// Identifies the Sogdian Unicode script.
    /// </summary>
    Sogdian,

    /// <summary>
    /// Identifies the SoraSompeng Unicode script.
    /// </summary>
    SoraSompeng,

    /// <summary>
    /// Identifies the Soyombo Unicode script.
    /// </summary>
    Soyombo,

    /// <summary>
    /// Identifies the Sundanese Unicode script.
    /// </summary>
    Sundanese,

    /// <summary>
    /// Identifies the Sunuwar Unicode script.
    /// </summary>
    Sunuwar,

    /// <summary>
    /// Identifies the SylotiNagri Unicode script.
    /// </summary>
    SylotiNagri,

    /// <summary>
    /// Identifies the Syriac Unicode script.
    /// </summary>
    Syriac,

    /// <summary>
    /// Identifies the Tagalog Unicode script.
    /// </summary>
    Tagalog,

    /// <summary>
    /// Identifies the Tagbanwa Unicode script.
    /// </summary>
    Tagbanwa,

    /// <summary>
    /// Identifies the TaiLe Unicode script.
    /// </summary>
    TaiLe,

    /// <summary>
    /// Identifies the TaiTham Unicode script.
    /// </summary>
    TaiTham,

    /// <summary>
    /// Identifies the TaiViet Unicode script.
    /// </summary>
    TaiViet,

    /// <summary>
    /// Identifies the Takri Unicode script.
    /// </summary>
    Takri,

    /// <summary>
    /// Identifies the Tamil Unicode script.
    /// </summary>
    Tamil,

    /// <summary>
    /// Identifies the Tangsa Unicode script.
    /// </summary>
    Tangsa,

    /// <summary>
    /// Identifies the Tangut Unicode script.
    /// </summary>
    Tangut,

    /// <summary>
    /// Identifies the Telugu Unicode script.
    /// </summary>
    Telugu,

    /// <summary>
    /// Identifies the Thaana Unicode script.
    /// </summary>
    Thaana,

    /// <summary>
    /// Identifies the Thai Unicode script.
    /// </summary>
    Thai,

    /// <summary>
    /// Identifies the Tibetan Unicode script.
    /// </summary>
    Tibetan,

    /// <summary>
    /// Identifies the Tifinagh Unicode script.
    /// </summary>
    Tifinagh,

    /// <summary>
    /// Identifies the Tirhuta Unicode script.
    /// </summary>
    Tirhuta,

    /// <summary>
    /// Identifies the Todhri Unicode script.
    /// </summary>
    Todhri,

    /// <summary>
    /// Identifies the Toto Unicode script.
    /// </summary>
    Toto,

    /// <summary>
    /// Identifies the TuluTigalari Unicode script.
    /// </summary>
    TuluTigalari,

    /// <summary>
    /// Identifies the Ugaritic Unicode script.
    /// </summary>
    Ugaritic,

    /// <summary>
    /// Identifies the Vai Unicode script.
    /// </summary>
    Vai,

    /// <summary>
    /// Identifies the Vithkuqi Unicode script.
    /// </summary>
    Vithkuqi,

    /// <summary>
    /// Identifies the Wancho Unicode script.
    /// </summary>
    Wancho,

    /// <summary>
    /// Identifies the WarangCiti Unicode script.
    /// </summary>
    WarangCiti,

    /// <summary>
    /// Identifies the Yezidi Unicode script.
    /// </summary>
    Yezidi,

    /// <summary>
    /// Identifies the Yi Unicode script.
    /// </summary>
    Yi,

    /// <summary>
    /// Identifies the ZanabazarSquare Unicode script.
    /// </summary>
    ZanabazarSquare,
}
