namespace Scout;

/// <summary>
/// Verifies independent records are partitioned into exact ASCII and non-ASCII runs.
/// </summary>
[TestClass]
public sealed class AsciiRecordRunEnumeratorTests
{
    /// <summary>
    /// Verifies line-feed and NUL record terminators produce equivalent partitions.
    /// </summary>
    /// <param name="terminator">The record terminator.</param>
    [TestMethod]
    [DataRow((byte)'\n')]
    [DataRow((byte)0)]
    public void SupportsLineFeedAndNullTerminators(byte terminator)
    {
        byte[] records = JoinRecords(
            terminator,
            "alpha"u8.ToArray(),
            [0xC3, 0xA9],
            "omega"u8.ToArray());

        AssertRuns(records, terminator,
            (0, 6, true),
            (6, 3, false),
            (9, 6, true));
    }

    /// <summary>
    /// Verifies an unterminated final record remains part of the final run.
    /// </summary>
    [TestMethod]
    public void PreservesFinalUnterminatedRecord()
    {
        byte[] records = [.. "alpha\n"u8, 0xFF, (byte)'z'];

        AssertRuns(records, (byte)'\n',
            (0, 6, true),
            (6, 2, false));
    }

    /// <summary>
    /// Verifies carriage returns are ordinary ASCII bytes in line-feed records.
    /// </summary>
    [TestMethod]
    public void TreatsCarriageReturnAsAsciiContent()
    {
        byte[] records = "alpha\r\nbeta\r\n"u8.ToArray();

        AssertRuns(records, (byte)'\n', (0, records.Length, true));
    }

    /// <summary>
    /// Verifies invalid UTF-8 and high bytes at record boundaries classify only their records.
    /// </summary>
    [TestMethod]
    public void IsolatesHighBytesAtRecordBoundaries()
    {
        byte[] records =
        [
            0x80, (byte)'a', (byte)'\n',
            (byte)'b', 0xFF, (byte)'\n',
            (byte)'c', (byte)'\n',
            0xFE, (byte)'\n',
            (byte)'d'
        ];

        AssertRuns(records, (byte)'\n',
            (0, 3, false),
            (3, 3, false),
            (6, 2, true),
            (8, 2, false),
            (10, 1, true));
    }

    /// <summary>
    /// Verifies entirely ASCII input is returned as one maximal run.
    /// </summary>
    [TestMethod]
    public void CoalescesAllAsciiRecords()
    {
        byte[] records = "a\n\nbeta\ngamma"u8.ToArray();

        AssertRuns(records, (byte)'\n', (0, records.Length, true));
    }

    /// <summary>
    /// Verifies each non-ASCII record is returned individually.
    /// </summary>
    [TestMethod]
    public void SeparatesAllNonAsciiRecords()
    {
        byte[] records = [0x80, (byte)'\n', 0x81, (byte)'x', (byte)'\n', 0x82];

        AssertRuns(records, (byte)'\n',
            (0, 2, false),
            (2, 3, false),
            (5, 1, false));
    }

    /// <summary>
    /// Verifies alternating ASCII and non-ASCII records retain one run per classification change.
    /// </summary>
    [TestMethod]
    public void PartitionsAlternatingRecords()
    {
        byte[] records =
        [
            (byte)'a', (byte)'\n',
            0x80, (byte)'\n',
            (byte)'b', (byte)'\n',
            0x81, (byte)'\n',
            (byte)'c'
        ];

        AssertRuns(records, (byte)'\n',
            (0, 2, true),
            (2, 2, false),
            (4, 2, true),
            (6, 2, false),
            (8, 1, true));
    }

    /// <summary>
    /// Verifies every generated byte sequence is reconstructed without gaps or overlap.
    /// </summary>
    [TestMethod]
    public void ExhaustivelyReconstructsGeneratedRecords()
    {
        byte[] alphabet = [(byte)'a', (byte)'\r', (byte)'\n', 0, 0x80, 0xFF];
        for (int length = 0; length <= 6; length++)
        {
            int combinations = 1;
            for (int index = 0; index < length; index++)
            {
                combinations *= alphabet.Length;
            }

            for (int value = 0; value < combinations; value++)
            {
                byte[] records = new byte[length];
                int remaining = value;
                for (int index = 0; index < records.Length; index++)
                {
                    records[index] = alphabet[remaining % alphabet.Length];
                    remaining /= alphabet.Length;
                }

                VerifyReconstruction(records, (byte)'\n');
                VerifyReconstruction(records, 0);
            }
        }
    }

    /// <summary>
    /// Verifies unsupported record terminators are rejected.
    /// </summary>
    [TestMethod]
    public void RejectsUnsupportedTerminator()
    {
        Assert.ThrowsExactly<ArgumentOutOfRangeException>(() => Enumerate("a|"u8, (byte)'|'));
    }

    private static void AssertRuns(
        ReadOnlySpan<byte> records,
        byte terminator,
        params (int Offset, int Length, bool IsAscii)[] expected)
    {
        (int Offset, int Length, bool IsAscii)[] actual = Enumerate(records, terminator);

        Assert.AreSequenceEqual(expected, actual);
        VerifyReconstruction(records, terminator);
    }

    private static (int Offset, int Length, bool IsAscii)[] Enumerate(
        ReadOnlySpan<byte> records,
        byte terminator)
    {
        var actual = new List<(int Offset, int Length, bool IsAscii)>();
        var enumerator = new AsciiRecordRunEnumerator(records, terminator);
        while (enumerator.MoveNext())
        {
            AsciiRecordRun run = enumerator.Current;
            actual.Add((run.Offset, run.Length, run.IsAscii));
        }

        return actual.ToArray();
    }

    private static void VerifyReconstruction(ReadOnlySpan<byte> records, byte terminator)
    {
        var enumerator = new AsciiRecordRunEnumerator(records, terminator);
        int expectedOffset = 0;
        bool previousWasAscii = false;
        while (enumerator.MoveNext())
        {
            AsciiRecordRun current = enumerator.Current;
            Assert.AreEqual(expectedOffset, current.Offset);
            Assert.IsGreaterThan(0, current.Length);

            ReadOnlySpan<byte> run = records.Slice(current.Offset, current.Length);
            if (current.IsAscii)
            {
                Assert.IsFalse(previousWasAscii);
                Assert.AreEqual(-1, run.IndexOfAnyExceptInRange((byte)0x00, (byte)0x7F));
            }
            else
            {
                Assert.AreNotEqual(-1, run.IndexOfAnyExceptInRange((byte)0x00, (byte)0x7F));
                Assert.AreEqual(-1, run[..^1].LastIndexOf(terminator));
            }

            expectedOffset += current.Length;
            if (expectedOffset < records.Length)
            {
                Assert.AreEqual(terminator, run[^1]);
            }

            previousWasAscii = current.IsAscii;
        }

        Assert.HasCount(expectedOffset, records);
    }

    private static byte[] JoinRecords(
        byte terminator,
        params byte[][] records)
    {
        using var stream = new MemoryStream();
        foreach (byte[] record in records)
        {
            stream.Write(record);
            stream.WriteByte(terminator);
        }

        return stream.ToArray();
    }
}
