namespace Scout;

internal enum RegexEngineKind
{
    LiteralSet,
    AlternationSet,
    WholeLine,
    DotStar,
    Ipv4Address,
    EmailAddress,
    Uri,
    WordWhitespaceLiteral,
    RunLiteralDotStar,
    LiteralPrefixRun,
    BoundedLiteralGap,
    BoundedLineLiteralGap,
    BoundedByteClassSequence,
    RepeatedLazyDotStarLiteral,
    LeadingClassLiteral,
    UnicodeLetterLiteralRun,
    WordBoundaryLiteralSet,
    WordSuffixLiteral,
    SimpleSequence,
    EndAnchoredSequence,
    EndAnchoredAtom,
    LineContains,
    DotStarClassFallback,
    PikeVm,
    BoundedBacktracker,
    OnePassDfa,
    DenseDfa,
    SparseDfa,
    LazyDfa,
}
